// Code generated by "stringer -type=Step"; DO NOT EDIT

package nodester

import "fmt"

const _Step_name = "UnpackCompileConfigureBuildInstall"

var _Step_index = [...]uint8{0, 6, 13, 22, 27, 34}

func (i Step) String() string {
	if i < 0 || i >= Step(len(_Step_index)-1) {
		return fmt.Sprintf("Step(%d)", i)
	}
	return _Step_name[_Step_index[i]:_Step_index[i+1]]
}
